name: build

on:
  push:
    branches:
      - main  # Spremeni, če uporabljaš drug branch

jobs:
    activate:
    runs-on: ubuntu-latest
    steps:
      - name: Request activation file
        uses: game-ci/unity-activation-request@v2
        with:
          unityVersion: 6000.0.37f1

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: unity-activation-file
          path: unity_v6000.0.37f1.alf

    build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - StandaloneOSX
          - WebGL

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: 6000.0.37f1  # Usklajeno z zgornjo vrednostjo
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

